### PR TITLE
fix: save/restore physical positions, closes #45

### LINKED ISSUE #45: [BUG] App does not resize when opened from a monitor different from the one it closed in
When I close the app in monitor B after resizing, and then open the app from monitor A, the app opens up on monitor B in the same position except it does not get resized. When I open the app from the same monitor as the monitor I closed the app in, the resizing works as expected even after closing the window that was not resized.

App source (please do not use the provided binary) https://github.com/elibroftw/google-keep-desktop-app

Screenshots of Behaviour

Window in right monitor before close 
image
Opening app from left monitor
image
Window opens up right monitor but not resized
image
Closed the window and now opening it from the right monitor
image
Window appears properly resized even after being closed with the wrong size
image

### LINKED ISSUE #244: [window-state] App does not resize when opened from a monitor different from the one it closed in
When I close the app in monitor B after resizing, and then open the app from monitor A, the app opens up on monitor B in the same position except it does not get resized. When I open the app from the same monitor as the monitor I closed the app in, the resizing works as expected even after closing the window that was not resized.

App source (please do not use the provided binary) https://github.com/elibroftw/google-keep-desktop-app

Screenshots of Behaviour

Window in right monitor before close 
image
Opening app from left monitor
image
Window opens up right monitor but not resized
image
Closed the window and now opening it from the right monitor
image
Window appears properly resized even after being closed with the wrong size
image

### PR DESCRIPTION
**Pull request by elibroftw**
Closes tauri-apps/plugins-workspace#244 

The app now remains in the same position regardless of which monitor the app was opened in.
Additionally, I removed the default (100, 100) position so that if no .window-state file exists or the monitor was disconnected, the window will open more naturally on the desktop and not mechanically as done with the (100, 100) offset.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -97,31 +97,19 @@ impl<R: Runtime> WindowExt for Window<R> {
...
+      // restore position to saved value if saved monitor exists
+      //  otherwise, let the OS decide where to place the window
+      for m in self.available_monitors()? {
+        if m.name().map(ToString::to_string).unwrap_or_default() == state.monitor {
+          self.set_position(PhysicalPosition { x: state.x, y: state.y })?;
+          break;
         }
-      };
-      self.set_position(LogicalPosition { x, y })?;
+      }
```
Comment (amrbashir) [inline src/lib.rs:112]: Really good, if we don't find the last saved monitor, it defaults to the OS position.

**Review by amrbashir — APPROVED** [review]
Thanks

**Comment by amrbashir** [comment]
The fallback to the OS is a really nice addition, thanks.
