### PR TITLE
fix: fix storing invalid values when window is minimized, closes #3

### LINKED ISSUE #3: On Windows, closing a minimized window causes the app to be stuck in an invalid state
On Windows, minimizing an app causes a `WindowEvent::Resized` event to be fired with `{width: 0, height: 0}` and a `WindowEvent::Moved` event to be fired with `{x: -32000, y: -32000}` (not sure if that's a static value or somehow related to monitor size). If the window is closed while minimized, the plugin persists these values to disk which causes the app to be stuck in an invisible state until the `.window-state` file is deleted. I also tested this on Linux and neither event is fired on minimize so it doesn't cause an issue. I'd be happy to attempt to fix this, but not sure if this is something that should be fixed upstream in Tao. Thanks!

Tauri info:
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 94.0.992.47

Node.js environment
  Node.js - 16.6.2
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.3
  yarn - 1.22.11

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -78,18 +78,36 @@ impl<R: Runtime> Plugin<R> for WindowState {
...
-                state.x = position.x;
-                state.y = position.y;
+                let size = window_clone.inner_size().unwrap();
+                // On some platforms, when a window gets minimized, it will report a
+                // position with a huge negative value (-32000), so for now
+                // don't save the position if the window is not visible on screen.
+                // also subtract a 25px, just to ensure there is enough space to
+                // be able to resize the window.
+                // TODO: use `window.is_minimized()` once it is implemented
+                if position.x > 0 - size.width as i32 - 25
```
Comment (FabianLars) [inline src/lib.rs]: Hmm this will conflict with multi-monitor setups i think. For example (on windows) if i move the window to the monitor on the left side of the primary one the reported position is `x: -1567, y: 171`.

but in general, that's not the only multi monitor problem we have (for example if you unplug a monitor), sooo idk.

Comment (amrbashir) [reply src/lib.rs]: I had multi-monitor in mind when I wrote this but assumed that `0,0` is the coordinates of the left-most monitor

Comment (amrbashir) [reply src/lib.rs]: I guess I can get the monitor handle and adjust the logic accordingly

Comment (FabianLars) [reply src/lib.rs]: I think linux starts at 0,0. Or at least x does. But y can still be negative iirc.

Comment (amrbashir) [reply src/lib.rs]: I don't have a multi monitor setup, can you test if it works ?

Comment (FabianLars) [reply src/lib.rs]: Works perfect on windows 👍 played around with some weird monitor positioning (including x **and** y), all good (well of course with the unpluggin thing).
I probably can test linux later today too.

Comment (amrbashir) [reply src/lib.rs]: thanks, appreciate your help

Comment (FabianLars) [reply src/lib.rs]: Hmm, linux (wayland) doesn't work, because the Moved event always reports a **window** position of 0,0. But the monitor sizes/positions never get below 0 so i think it should work once the window position works again :thinking:

Comment (amrbashir) [reply src/lib.rs]: does the moved event work correctly on wayland in tao or in tauri events ?

Comment (FabianLars) [reply src/lib.rs]: it's broken in tao too and it looks like i have to trigger another event to get the moved event fired. Speaking of which, it also looks like the moved event gets triggered on every other window event too (for example resizing and blur/focus triggers it too.

Edit: X11 works fine.

Comment (amrbashir) [reply src/lib.rs]: Alright, I will consider this PR is working well and ready to go. please open an issue with your findings on tao for the moved event.
